name: Setup custom CLI tooling in a custom action
description: Installs the golangci-lint as custom tooling and adds it to the PATH, making it available to runners
author: travboz

inputs:
  version:
    description: The version of `golangci-lint` to install
    required: true

runs:
  using: node20
  main: index.js

branding:
  icon: "terminal"
  color: "purple"
